- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
      - name: create ec2 instance
        ec2:
          aws_access_key: "AKIAWJOLIMJTHO7IQEE7"
          aws_secret_key: "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"
          image: ami-07d0cf3af28718ef8
          wait: yes
          instance_type: t2.micro
          group_id: sg-0958d3fa266d68022
          region: us-east-1
          keypair: prasadnvarginia
          count_tag:
            Name: apacheserver
          exact_count: 1
          instance_tags:
             db: postgres
        register: ec2
