---
- hosts: webserver
  become: yes
  tasks:

  - name: install java
    apt: name=openjdk-11-jre state=present updte_cache=yes

  - name: Install EPEL repo.
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

  - name: Install tomcat
    yum: name=tomcat state=present update_cache=yes


  - name: Install tomcat webapps
    yum: name=tomcat-webapps 

  - name: Install tomcat admin-webapps
    yum: name=tomcat-admin-webapps state=present
